import {
  UserProfile,
  Post,
  Moment,
  Conversation,
  Message,
  Space,
  ListeningSession,
  Community,
  LiveVoiceRoom,
  NotificationItem,
  Playlist,
  Track,
} from "@/types";

import { MOCK_TRACKS } from "./music-provider";
export { MOCK_TRACKS };


export const KUTTI_STORY_TRACK: Track = {
  id: "GqlGdhjEXNg",
  title: "Kutti Story (From \"Master\")",
  artist: "Anirudh Ravichander, Thalapathy Vijay",
  album: "Master",
  coverArt: "https://img.youtube.com/vi/GqlGdhjEXNg/hqdefault.jpg",
  duration: 290,
  audioUrl: "https://www.youtube-nocookie.com/embed/GqlGdhjEXNg",
  genre: "Tamil Pop",
  releaseYear: 2021,
};

export const CURRENT_USER: UserProfile = {
  id: "usr-me",
  name: "Alex Rivera",
  username: "alex_vibes",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=250&auto=format&fit=crop",
  coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
  bio: "Music addict 🎧 | Long-distance dreamer ✨ | Synthwave & Tamil Indie lover 🌙",
  followersCount: 1420,
  followingCount: 380,
  postsCount: 42,
  interests: ["Live Music", "Coding", "Lo-Fi Beats", "Stargazing", "Photography"],
  favoriteGenres: ["Synthwave", "Lo-Fi", "Tamil Indie", "EDM", "Acoustic Pop"],
  favoriteArtists: ["Aether & Kael", "Luna Chill", "Anirudh", "The Midnight"],
  publicPlaylistsCount: 6,
  privacy: "public",
  joinedDate: "February 2024",
  onlineStatus: "online",
  currentTrack: KUTTI_STORY_TRACK,
};

export const SAM_PROFILE: UserProfile = {
  id: "usr-sam",
  name: "Sam Chen",
  username: "sam_melody",
  avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=250&auto=format&fit=crop",
  coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop",
  bio: "Architect by day, vinyl collector by night 🎹 | Alex's player two ❤️",
  followersCount: 980,
  followingCount: 240,
  postsCount: 29,
  interests: ["Vinyls", "Architecture", "Lo-Fi", "Coffee", "Cozy Gaming"],
  favoriteGenres: ["Lo-Fi", "Indie Rock", "Ambient", "Tamil Indie"],
  favoriteArtists: ["Luna Chill", "Varun & Ananya", "Pradeep Kumar"],
  publicPlaylistsCount: 4,
  privacy: "public",
  joinedDate: "March 2024",
  onlineStatus: "listening",
  currentTrack: MOCK_TRACKS[1],
  isFollowing: true,
};

export const MOCK_USERS: UserProfile[] = [
  CURRENT_USER,
  SAM_PROFILE,
  {
    id: "usr-priya",
    name: "Priya Sharma",
    username: "priya_beats",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=250&auto=format&fit=crop",
    bio: "Curator of late-night vibes 🌌 | Chennai -> Seattle ✈️",
    followersCount: 3200,
    followingCount: 510,
    postsCount: 88,
    interests: ["Concerts", "Tamil Pop", "Podcasts"],
    favoriteGenres: ["Tamil Indie", "Pop", "R&B"],
    favoriteArtists: ["Anirudh", "Sid Sriram"],
    publicPlaylistsCount: 12,
    privacy: "public",
    joinedDate: "January 2024",
    onlineStatus: "online",
    isFollowing: true,
  },
  {
    id: "usr-john",
    name: "John Miller",
    username: "john_synth",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=250&auto=format&fit=crop",
    bio: "Synthesizer producer & audio nerd 🎛️",
    followersCount: 4100,
    followingCount: 310,
    postsCount: 104,
    interests: ["Modular Synths", "EDM", "Sound Design"],
    favoriteGenres: ["Synthwave", "EDM", "Cyberpunk"],
    favoriteArtists: ["Kavinsky", "Daft Punk"],
    publicPlaylistsCount: 15,
    privacy: "public",
    joinedDate: "December 2023",
    onlineStatus: "offline",
    isFollowing: false,
  },
  {
    id: "usr-arun",
    name: "Arun Kumar",
    username: "arun_grooves",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=250&auto=format&fit=crop",
    bio: "Bass guitar enthusiast 🎸 | Gaming with background music",
    followersCount: 850,
    followingCount: 190,
    postsCount: 18,
    interests: ["Bass", "Valorant", "Rock"],
    favoriteGenres: ["Rock", "Metal", "Lo-Fi"],
    favoriteArtists: ["Red Hot Chili Peppers", "Polyphia"],
    publicPlaylistsCount: 3,
    privacy: "public",
    joinedDate: "April 2024",
    onlineStatus: "online",
    isFollowing: true,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "post-1",
    author: SAM_PROFILE,
    createdAt: "15m ago",
    content: "Nothing hits harder on a late Friday night than synchronized Lo-Fi listening across time zones. Listening to this continuous ambient stream with Alex ❤️🎧",
    musicCard: {
      track: MOCK_TRACKS[1],
      sharedNote: "Press Play to listen with us right now!",
    },
    likesCount: 48,
    commentsCount: 12,
    sharesCount: 5,
    isLiked: true,
    comments: [
      {
        id: "c-1",
        author: CURRENT_USER,
        content: "Best part of my day! ❤️✨",
        createdAt: "10m ago",
        likesCount: 4,
        isLiked: true,
      },
      {
        id: "c-2",
        author: MOCK_USERS[2],
        content: "Adding this track to my late night reading playlist!",
        createdAt: "5m ago",
        likesCount: 2,
      },
    ],
  },
  {
    id: "post-2",
    author: MOCK_USERS[2],
    createdAt: "2h ago",
    content: "Which vibe should we play for tonight's Tamil Music Listening Party in our community space?",
    poll: {
      question: "Tonight's Room Vibe:",
      options: [
        { id: "opt-1", text: "Acoustic & Soft Indie Vibes 🎸", votes: 84 },
        { id: "opt-2", text: "High Energy Anirudh Beat Drops 🔥", votes: 142 },
        { id: "opt-3", text: "Retro 90s Nostalgic Classics 📻", votes: 61 },
      ],
      totalVotes: 287,
      userVotedOptionId: "opt-2",
    },
    likesCount: 112,
    commentsCount: 24,
    sharesCount: 18,
    isLiked: false,
  },
  {
    id: "post-3",
    author: MOCK_USERS[3],
    createdAt: "4h ago",
    content: "Just finished producing this new synthwave track 'Midnight City Lights'! The bass synth was synthesized using vintage analog oscillators. Let me know what you think!",
    media: [
      {
        type: "image",
        url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1000&auto=format&fit=crop",
      },
    ],
    musicCard: {
      track: MOCK_TRACKS[0],
    },
    likesCount: 230,
    commentsCount: 45,
    sharesCount: 32,
    isLiked: true,
    isSaved: true,
  },
];

export const MOCK_MOMENTS: Moment[] = [
  {
    id: "mom-1",
    author: SAM_PROFILE,
    type: "music",
    track: MOCK_TRACKS[1],
    caption: "Late night coffee & cozy beats ☕🎶",
    createdAt: "1h ago",
    expiresAt: "23h remaining",
    reactionsCount: 14,
  },
  {
    id: "mom-2",
    author: MOCK_USERS[2],
    type: "photo",
    mediaUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=600&auto=format&fit=crop",
    caption: "Soundcheck for tonight's community voice room! 🎙️",
    createdAt: "3h ago",
    expiresAt: "21h remaining",
    reactionsCount: 28,
  },
  {
    id: "mom-3",
    author: MOCK_USERS[3],
    type: "music",
    track: MOCK_TRACKS[0],
    caption: "Synthesizing neon waves 🎛️⚡",
    createdAt: "5h ago",
    expiresAt: "19h remaining",
    reactionsCount: 42,
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-maya",
    isGroup: false,
    unreadCount: 0,
    members: [
      CURRENT_USER,
      {
        id: "usr-maya",
        name: "Maya Vance ✨",
        username: "maya_beats.lofi",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=250&auto=format&fit=crop",
        bio: "Lo-Fi Producer & Sound Designer 🎧",
        followersCount: 18500,
        followingCount: 420,
        postsCount: 154,
        interests: ["Lo-Fi", "Synth", "Sound Design"],
        favoriteGenres: ["Lo-Fi Beats", "Ambient"],
        favoriteArtists: ["Luna Chill", "Aether & Kael"],
        publicPlaylistsCount: 8,
        privacy: "public",
        joinedDate: "January 2024",
        onlineStatus: "online",
      },
    ],
    lastMessage: {
      id: "m-maya-last",
      senderId: CURRENT_USER.id,
      senderName: CURRENT_USER.name,
      senderAvatar: CURRENT_USER.avatar,
      content: "You: Ready now! Joining room ✨",
      timestamp: "2m",
      type: "text",
    },
  },
  {
    id: "conv-devon",
    isGroup: false,
    unreadCount: 0,
    members: [
      CURRENT_USER,
      {
        id: "usr-devon",
        name: "Devon Reed 🎸",
        username: "devon_grooves",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=250&auto=format&fit=crop",
        bio: "Indie Rock Guitarist 🎸",
        followersCount: 14200,
        followingCount: 310,
        postsCount: 92,
        interests: ["Guitars", "Rock"],
        favoriteGenres: ["Indie Rock", "Acoustic"],
        favoriteArtists: ["Polyphia"],
        publicPlaylistsCount: 11,
        privacy: "public",
        joinedDate: "February 2024",
        onlineStatus: "online",
      },
    ],
    lastMessage: {
      id: "m-dev-1",
      senderId: CURRENT_USER.id,
      senderName: CURRENT_USER.name,
      senderAvatar: CURRENT_USER.avatar,
      content: "You sent a music session invite.",
      timestamp: "12m",
      type: "text",
    },
  },
  {
    id: "conv-aria",
    isGroup: false,
    unreadCount: 0,
    members: [
      CURRENT_USER,
      {
        id: "usr-aria",
        name: "Aria Chen 🌙",
        username: "aria_acoustic",
        avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=250&auto=format&fit=crop",
        bio: "Vocalist & Songwriter 🎤",
        followersCount: 32000,
        followingCount: 290,
        postsCount: 180,
        interests: ["Vocals", "Piano"],
        favoriteGenres: ["Acoustic Pop", "R&B"],
        favoriteArtists: ["Anirudh"],
        publicPlaylistsCount: 9,
        privacy: "public",
        joinedDate: "March 2024",
        onlineStatus: "offline",
      },
    ],
    lastMessage: {
      id: "m-[#aria-1",
      senderId: "usr-aria",
      senderName: "Aria Chen 🌙",
      senderAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=250&auto=format&fit=crop",
      content: "Aria sent a audio clip.",
      timestamp: "45m",
      type: "text",
    },
  },
  {
    id: "conv-pixel",
    isGroup: false,
    unreadCount: 1,
    members: [
      CURRENT_USER,
      {
        id: "usr-pixel",
        name: "Pixel & Synth 🎛️",
        username: "pixel_synth_official",
        avatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=250&auto=format&fit=crop",
        bio: "Modular Synthesizer Lab & Beats 🎛️",
        followersCount: 45000,
        followingCount: 120,
        postsCount: 310,
        interests: ["Synths", "EDM", "Cyberpunk"],
        favoriteGenres: ["Synthwave", "Cyberpunk"],
        favoriteArtists: ["Kavinsky", "Daft Punk"],
        publicPlaylistsCount: 15,
        privacy: "public",
        joinedDate: "January 2024",
        onlineStatus: "online",
      },
    ],
    lastMessage: {
      id: "m-pix-1",
      senderId: "usr-pixel",
      senderName: "Pixel & Synth 🎛️",
      senderAvatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=250&auto=format&fit=crop",
      content: "Pixel & Synth sent a project stem.",
      timestamp: "2h",
      type: "text",
    },
  },
  {
    id: "conv-liam",
    isGroup: false,
    unreadCount: 0,
    members: [
      CURRENT_USER,
      {
        id: "usr-liam",
        name: "Liam K. 🎧",
        username: "liam_synthwave",
        avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=250&auto=format&fit=crop",
        bio: "Chillhop & Night Grooves 🌙",
        followersCount: 9400,
        followingCount: 210,
        postsCount: 64,
        interests: ["Chillhop", "DJing"],
        favoriteGenres: ["Lo-Fi", "Chillhop"],
        favoriteArtists: ["Pradeep Kumar"],
        publicPlaylistsCount: 6,
        privacy: "public",
        joinedDate: "December 2023",
        onlineStatus: "offline",
      },
    ],
    lastMessage: {
      id: "m-liam-1",
      senderId: CURRENT_USER.id,
      senderName: CURRENT_USER.name,
      senderAvatar: CURRENT_USER.avatar,
      content: "You: Catch you at the voice stage! 🎙️",
      timestamp: "5h",
      type: "text",
    },
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "m-1",
    senderId: SAM_PROFILE.id,
    senderName: SAM_PROFILE.name,
    senderAvatar: SAM_PROFILE.avatar,
    content: "Hey Alex! Are you free for a quick listening session?",
    timestamp: "8:42 PM",
    type: "text",
  },
  {
    id: "m-2",
    senderId: CURRENT_USER.id,
    senderName: CURRENT_USER.name,
    senderAvatar: CURRENT_USER.avatar,
    content: "Always free for you! What are we listening to tonight?",
    timestamp: "8:43 PM",
    type: "text",
  },
  {
    id: "m-3",
    senderId: SAM_PROFILE.id,
    senderName: SAM_PROFILE.name,
    senderAvatar: SAM_PROFILE.avatar,
    content: "Check this new acoustic track out! I made a listening room.",
    timestamp: "8:44 PM",
    type: "listen-invite",
    listenSessionId: "session-couple-1",
    listenTrack: MOCK_TRACKS[1],
  },
];

export const MOCK_COUPLE_SPACE: Space = {
  id: "space-couple",
  name: "Alex ❤️ Sam Space",
  type: "couple",
  coverImage: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=1200&auto=format&fit=crop",
  icon: "❤️",
  isPrivate: true,
  description: "Our sacred digital hideaway. Syncing music & memories across 2,400 miles.",
  membersCount: 2,
  members: [CURRENT_USER, SAM_PROFILE],
  activeListeningSessionId: "session-couple-1",
  coupleData: {
    id: "couple-data-1",
    partner1: CURRENT_USER,
    partner2: SAM_PROFILE,
    relationshipStartDate: "2023-05-20",
    anniversaryTitle: "2nd Anniversary Countdown",
    anniversaryDate: "2025-05-20",
    streakDays: 452,
    moodPartner1: { emoji: "🥰", status: "Missing you extra today", updatedAt: "1h ago" },
    moodPartner2: { emoji: "☕", status: "Cozy reading & listening to Lo-Fi", updatedAt: "30m ago" },
    dailyQuestion: {
      question: "What song instantly reminds you of our first trip together?",
      answer1: "Alex: 'Midnight City Lights' playing on the midnight highway drive 🌌",
      answer2: "Sam: 'Starlight Coffee' when we sat by the beach cafe ☕🌊",
    },
    sharedMemories: [
      {
        id: "mem-1",
        title: "Beach Sunset Concert",
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
        date: "July 14, 2024",
        note: "We danced under the stars while listening to acoustic guitar.",
      },
      {
        id: "mem-2",
        title: "Cozy Rainy Day Vinyl Marathon",
        imageUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=800&auto=format&fit=crop",
        date: "November 2, 2024",
        note: "Listened to 5 albums back to back in our private listening session.",
      },
    ],
    couplePlaylists: [
      {
        id: "pl-couple-1",
        name: "Our Long Distance Anthems ✈️❤️",
        description: "Songs that bring us closer no matter the distance.",
        coverArt: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400",
        isPublic: false,
        owner: CURRENT_USER,
        collaborators: [SAM_PROFILE],
        tracks: [MOCK_TRACKS[0], MOCK_TRACKS[1], MOCK_TRACKS[2]],
        likesCount: 1,
        type: "couple",
      },
    ],
    sharedNotes: [
      { id: "sn-1", author: "Sam", content: "Remember to queue up 'Celestial Resonance' tonight!", date: "Today" },
    ],
  },
};

export const MOCK_SPACES: Space[] = [
  MOCK_COUPLE_SPACE,
  {
    id: "space-friends",
    name: "Midnight Vibes Squad 🌙",
    type: "best-friends",
    coverImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop",
    icon: "🎧",
    isPrivate: true,
    description: "Private room for our close inner circle listening parties and late night chats.",
    membersCount: 5,
    members: [CURRENT_USER, SAM_PROFILE, MOCK_USERS[2], MOCK_USERS[3], MOCK_USERS[4]],
    activeListeningSessionId: "session-group-1",
  },
  {
    id: "space-gaming",
    name: "Valorant & Beats Arena 🎮",
    type: "gaming",
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop",
    icon: "⚡",
    isPrivate: false,
    description: "High energy synthwave & EDM background streams for competitive gaming.",
    membersCount: 142,
    members: [CURRENT_USER, MOCK_USERS[3], MOCK_USERS[4]],
  },
];

export const INITIAL_LISTENING_SESSION: ListeningSession = {
  id: "session-couple-1",
  title: "Alex & Sam's Midnight Lounge 🌙",
  host: CURRENT_USER,
  coHosts: [SAM_PROFILE],
  participants: [CURRENT_USER, SAM_PROFILE, MOCK_USERS[2]],
  isPublic: false,
  roomCode: "VIBE-8842",
  playbackState: {
    sessionId: "session-couple-1",
    currentTrack: null,
    isPlaying: false,
    currentPosition: 0,
    playbackRate: 1.0,
    updatedAt: Date.now(),
    hostId: CURRENT_USER.id,
  },
  queue: [],
  controlMode: "everyone",
  liveChat: [
    { id: "lc-1", author: CURRENT_USER, text: "Welcome to our room! Synced listening activated 🟢", time: "8:45 PM", system: true },
    { id: "lc-2", author: SAM_PROFILE, text: "The synth drop on this song is incredible! 🔥", time: "8:46 PM" },
    { id: "lc-3", author: MOCK_USERS[2], text: "Priya joined the session 🎧", time: "8:47 PM", system: true },
    { id: "lc-4", author: MOCK_USERS[2], text: "Upvoted 'Starlight Coffee' for next up!", time: "8:48 PM" },
  ],
  currentReactions: [
    { id: "r-1", emoji: "❤️", userId: SAM_PROFILE.id, userName: "Sam", timestamp: Date.now() - 2000 },
    { id: "r-2", emoji: "🔥", userId: MOCK_USERS[2].id, userName: "Priya", timestamp: Date.now() - 1000 },
  ],
  syncStatus: "synced",
  driftMs: 14,
};

export const MOCK_COMMUNITIES: Community[] = [
  {
    id: "comm-tamil",
    name: "Tamil Music Lovers 🎵",
    handle: "tamil_vibes",
    avatar: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=300",
    banner: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200",
    description: "The largest hub for Tamil Indie, AR Rahman, Anirudh beat drops, and late-night listening rooms.",
    membersCount: 18400,
    isJoined: true,
    channels: [
      { id: "ch-general", name: "general", type: "text" },
      { id: "ch-new", name: "new-music", type: "text" },
      { id: "ch-playlists", name: "playlists", type: "text" },
      { id: "ch-memes", name: "memes", type: "text" },
      { id: "ch-voice", name: "🎙️ General Talk", type: "voice" },
      { id: "ch-music", name: "🎵 Friday Listening Party", type: "music" },
    ],
    moderators: [MOCK_USERS[2]],
    rules: [
      "1. Be respectful to all music genres and members.",
      "2. No spamming or unauthorized self-promotion.",
      "3. Share collaborative playlist links in #playlists only.",
    ],
  },
  {
    id: "comm-lofi",
    name: "Lo-Fi Study & Chill Society ☕",
    handle: "lofi_society",
    avatar: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=300",
    banner: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200",
    description: "24/7 relaxed synchronized listening streams for focus, programming, and cozy nights.",
    membersCount: 34200,
    isJoined: false,
    channels: [
      { id: "ch-lofi-gen", name: "general", type: "text" },
      { id: "ch-lofi-music", name: "🎵 24/7 LoFi Stream", type: "music" },
    ],
    moderators: [SAM_PROFILE],
    rules: ["1. Maintain relaxed vibes.", "2. Keep chat clean."],
  },
];

export const MOCK_VOICE_ROOMS: LiveVoiceRoom[] = [
  {
    id: "vr-1",
    title: "🎙️ Tamil Music Nostalgic Hits & Discussion",
    host: MOCK_USERS[2],
    coHosts: [CURRENT_USER],
    speakers: [MOCK_USERS[2], CURRENT_USER, SAM_PROFILE],
    listeners: [MOCK_USERS[3], MOCK_USERS[4]],
    isMusicConnected: true,
    connectedSession: INITIAL_LISTENING_SESSION,
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "n-1",
    type: "listen-invite",
    actor: SAM_PROFILE,
    text: "invited you to listen together in 'Alex & Sam's Midnight Lounge 🌙'",
    time: "2m ago",
    read: false,
    targetId: "session-couple-1",
  },
  {
    id: "n-2",
    type: "like",
    actor: MOCK_USERS[2],
    text: "liked your music post 'Midnight City Lights'",
    time: "15m ago",
    read: false,
  },
  {
    id: "n-3",
    type: "comment",
    actor: SAM_PROFILE,
    text: "commented: 'Best part of my day! ❤️✨'",
    time: "1h ago",
    read: true,
  },
  {
    id: "n-4",
    type: "follow",
    actor: MOCK_USERS[3],
    text: "started following you.",
    time: "3h ago",
    read: true,
  },
];
