server:
  port: 8085

spring:
  application:
    name: vibespace-backend
  datasource:
    url: jdbc:h2:mem:vibespacedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO
    com.vibespace: DEBUG
